/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipsl.edu.sn.InterfaceGraphique;

import ipsl.edu.sn.BasesDonnees.ConnectionBase;
import ipsl.edu.sn.BasesDonnees.InvalideException;
import ipsl.edu.sn.Entites.Etudiant;

import ipsl.edu.sn.Metier.ImplementationMetier;
import java.util.Date;
import ipsl.edu.sn.Metier.InterfaceMetier;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class InfoEtudiant extends javax.swing.JPanel {

    /**
     * Creates new form InfoEtudiant
     */
    public InfoEtudiant() {
        initComponents();
    }
    int id;
    ImplementationMetier Etudiant = new ImplementationMetier();
    ArrayList<Etudiant> liste = new ArrayList();
    static String g;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        errorPrenomLabel2 = new javax.swing.JLabel();
        prenomTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomTextField2 = new javax.swing.JTextField();
        errorNomLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateTextField3 = new javax.swing.JTextField();
        errorIDLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IDTextField4 = new javax.swing.JTextField();
        DeleteButton1 = new javax.swing.JButton();
        EnregistrerToggleButton1 = new javax.swing.JToggleButton();
        errordateLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRENOM");

        errorPrenomLabel2.setForeground(new java.awt.Color(255, 0, 51));
        errorPrenomLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        prenomTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOM");

        nomTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        errorNomLabel4.setForeground(new java.awt.Color(255, 0, 51));
        errorNomLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATE DE NAISSANCE");

        dateTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        errorIDLabel6.setForeground(new java.awt.Color(255, 51, 51));
        errorIDLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("IDENTIFIANT");

        IDTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DeleteButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteButton1.setText("ANNULER");
        DeleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton1ActionPerformed(evt);
            }
        });

        EnregistrerToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EnregistrerToggleButton1.setText("ENREGISTRER");
        EnregistrerToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerToggleButton1ActionPerformed(evt);
            }
        });

        errordateLabel2.setForeground(new java.awt.Color(255, 0, 51));
        errordateLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(errorNomLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(errorPrenomLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prenomTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeleteButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EnregistrerToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(errorIDLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(errordateLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDTextField4))))
                        .addGap(4, 4, 4))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenomTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(errorPrenomLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(errorNomLabel4)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(errordateLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(errorIDLabel6)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteButton1)
                    .addComponent(EnregistrerToggleButton1))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton1ActionPerformed
        prenomTextField1.setText("");
        nomTextField2.setText("");
        IDTextField4.setText("");

        dateTextField3.setText("");
    }//GEN-LAST:event_DeleteButton1ActionPerformed

    private void EnregistrerToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerToggleButton1ActionPerformed
        try {
            String PrenomEtudiant = prenomTextField1.getText();
            String NomEtudiant = nomTextField2.getText();
            String datenaissance = dateTextField3.getText();
            Date date = ConnectionBase.SQL_FORMAT.parse(datenaissance);

            String Id = IDTextField4.getText();

            try {
                String requete = "Select Identifiant From Etudiant";
                Connection connection = ConnectionBase.getConnection();
                Statement statement = connection.createStatement();
                ResultSet res = statement.executeQuery(requete);

                while (res.next()) {
                    Etudiant e1 = new Etudiant();

                    e1.setID(res.getString("Identifiant"));

                    liste.add(e1);

                }
                int i;
                for (i = 0; i < liste.size(); i++) {

                    g = liste.get(i).getID();

                    if (Id.equals(g)) {
                        System.out.println("hi");
                        JOptionPane.showMessageDialog(this, "L'identifiant existe deja", "formulaire invalide", JOptionPane.ERROR_MESSAGE);
                        return;

                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            Etudiant e = new Etudiant();
            e.setPrenomEtudiant(PrenomEtudiant);
            e.setNomEtudiant(NomEtudiant);

            e.setID(Id);
            e.setDateNaissance(date);
            try {
                Etudiant.sauvegarderEtudiant(e);

                prenomTextField1.setText("");
                nomTextField2.setText("");
                IDTextField4.setText("");
                dateTextField3.setText("");
                errorIDLabel6.setText("");
                errorNomLabel4.setText("");
                errorPrenomLabel2.setText("");
                errordateLabel2.setText("");
            } catch (InvalideException exp) {
                Logger.getLogger(InfoEtudiant.class.getName()).log(Level.SEVERE, null, exp);

                if (PrenomEtudiant.isBlank() || PrenomEtudiant == null) {
                    errorPrenomLabel2.setText(exp.getMessage());
                    return;
                }
                if (PrenomEtudiant != "" && PrenomEtudiant != null) {
                    errorPrenomLabel2.setText("");

                }
                if (NomEtudiant.isBlank() || NomEtudiant == null) {
                    errorNomLabel4.setText(exp.getMessage());
                    return;
                }
                if (NomEtudiant != "" && NomEtudiant != null) {
                    errorNomLabel4.setText("");

                }
                if (Id.isBlank() || Id == null) {
                    errorIDLabel6.setText(exp.getMessage());

                    return;
                }
                if (Id != "" && Id != null) {
                    errorIDLabel6.setText("");

                }

            }

        } catch (ParseException ex) {
            Logger.getLogger(InfoEtudiant.class.getName()).log(Level.SEVERE, null, ex);
            errordateLabel2.setText(ex.getMessage());

        }


    }//GEN-LAST:event_EnregistrerToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton1;
    private javax.swing.JToggleButton EnregistrerToggleButton1;
    private javax.swing.JTextField IDTextField4;
    private javax.swing.JTextField dateTextField3;
    private javax.swing.JLabel errorIDLabel6;
    private javax.swing.JLabel errorNomLabel4;
    private javax.swing.JLabel errorPrenomLabel2;
    private javax.swing.JLabel errordateLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nomTextField2;
    private javax.swing.JTextField prenomTextField1;
    // End of variables declaration//GEN-END:variables
}
