/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipsl.edu.sn.InterfaceGraphique;

import ipsl.edu.sn.BasesDonnees.ConnectionBase;
import ipsl.edu.sn.Entites.Etudiant;
import ipsl.edu.sn.Metier.ImplementationMetier;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author pc
 */
public class LISTEFILIERE extends javax.swing.JPanel {
    Etudiant e =new Etudiant();

    /**
     * Creates new form LISTEFILIERE
     */
    public LISTEFILIERE() {
        initComponents();
    }
    
    
public ArrayList<Etudiant> liste(Etudiant e){
    ArrayList<Etudiant> liste2=new ArrayList();
    
   String filiere= e.getFiliere();
    
    
         try{
             
             String requete= "SELECT NomFiliere,Nom FROM Filiere ,Etudiant  WHERE Etudiant.Identifiant=Filiere.Identifiant AND NomFiliere='"+filiere+"'";
            Connection connection=ConnectionBase.getConnection();
            Statement statement=connection.createStatement();
       ResultSet res=  statement.executeQuery(requete);

         while (res.next()) {
      Etudiant e1=new Etudiant();
     
             e1.setFiliere(res.getString("NomFiliere"));
             e1.setNomEtudiant(res.getString("Nom"));
            
             liste2.add(e1);
             
         }   
            
        }catch(Exception ex){
            ex.printStackTrace();
    }
        
         
        
     return  liste2;     
    
}
public void Showliste(){
    ArrayList<Etudiant> liste1=liste(e);
    
    DefaultTableModel model= new DefaultTableModel();
    model=(DefaultTableModel) jTableListe.getModel();
    Object[] row =new Object[2];
    for(int i =0; i<liste1.size();i++){
        row[1]=liste1.get(i).getFiliere();
        row[0]=liste1.get(i).getNomEtudiant();
        model.addRow(row);
    }
    
    
}
public void Effacer(){
     DefaultTableModel model= new DefaultTableModel();
    model=(DefaultTableModel) jTableListe.getModel();
    model.getDataVector().removeAllElements();
    
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VALIDEButton1 = new javax.swing.JButton();
        FILIERETextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListe = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("    FILIERE");

        VALIDEButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VALIDEButton1.setText("ENREGISTRER");
        VALIDEButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VALIDEButton1ActionPerformed(evt);
            }
        });

        FILIERETextField1.setText(" ");
        FILIERETextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FILIERETextField1ActionPerformed(evt);
            }
        });

        jTableListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOM", "FILIERE"
            }
        ));
        jScrollPane1.setViewportView(jTableListe);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("ANNULER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FILIERETextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VALIDEButton1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FILIERETextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VALIDEButton1)
                    .addComponent(jButton1))
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VALIDEButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VALIDEButton1ActionPerformed
          String filiere1 =FILIERETextField1.getText();
          e.getFiliere();
          e.setFiliere(filiere1);
          Showliste();
             FILIERETextField1.setText("");

    }//GEN-LAST:event_VALIDEButton1ActionPerformed

    private void FILIERETextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FILIERETextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FILIERETextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         FILIERETextField1.setText("");
        DefaultTableModel model= new DefaultTableModel();
    model=(DefaultTableModel) jTableListe.getModel();
   model.setRowCount(0);
    
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FILIERETextField1;
    private javax.swing.JButton VALIDEButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListe;
    // End of variables declaration//GEN-END:variables
}
