/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipsl.edu.sn.InterfaceGraphique;

import ipsl.edu.sn.Entites.Etudiant;
import ipsl.edu.sn.Metier.ImplementationMetier;

/**
 *
 * @author pc
 */
public class SuppressionFiliere extends javax.swing.JPanel {

    /**
     * Creates new form SuppressionFiliere
     */
    public SuppressionFiliere() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDEntifiantTextField1 = new javax.swing.JTextField();
        SAVEButton1 = new javax.swing.JButton();
        DELETEButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("     FILIERE:");

        IDEntifiantTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        SAVEButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SAVEButton1.setText("ENREGISTRER");
        SAVEButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEButton1ActionPerformed(evt);
            }
        });

        DELETEButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DELETEButton2.setText("ANNULER");
        DELETEButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(DELETEButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(SAVEButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(IDEntifiantTextField1)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDEntifiantTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DELETEButton2)
                    .addComponent(SAVEButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SAVEButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEButton1ActionPerformed
      String filiere=IDEntifiantTextField1.getText();
Etudiant e =new Etudiant();
e.setFiliere(filiere);
ImplementationMetier Etudiant=new ImplementationMetier();
Etudiant.SupprimerFiliere(e);
IDEntifiantTextField1.setText("");
    }//GEN-LAST:event_SAVEButton1ActionPerformed

    private void DELETEButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEButton2ActionPerformed
       IDEntifiantTextField1.setText("");
    }//GEN-LAST:event_DELETEButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETEButton2;
    private javax.swing.JTextField IDEntifiantTextField1;
    private javax.swing.JButton SAVEButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
